### ISSUE TITLE
Pass plan file to apply command

### ISSUE THREAD

**Issue by unthar** [infrablocks/ruby_terraform#14]
Hey, Toby,
I was trying to figure out a way to pass a plan file that was created with the 'plan' command to the 'apply' command. I didn't see an option to 'apply' for this. I started messing around with the apply.rb code to add a plan file option. Since the 'directory' option is required my changes failed, however, I realized then that I could just pass the plan file to the 'directory' option and it worked.

```
RubyTerraform.apply(
    directory: '_path/plan_file_'
  )

```
Is this the intended use for the 'directory' option with apply? If so, should the README be updated to reflect that? I read it as the directory of the terraform code just like with the plan command. 

Thanks for the great module!

Kevin

**Comment by unthar** [comment]
Hey, Toby,
Sorry I haven't gotten back to you sooner. I'll try and get a PR together when I get a chance.

Thanks!

**Comment by tobyclemson** [comment]
No problem, whenever you get a chance.

In terms of `directory` being required I think we can make it optional in this PR or maybe even just check for the presence of one of `directory` or `plan`.

Thanks,
Toby

**Comment by tobyclemson** [comment]
I've added this in version [0.32.0](https://rubygems.org/gems/ruby-terraform/versions/0.32.0).
