### ISSUE TITLE
Add missing parameters to all implemented commands

### ISSUE THREAD

**Issue by tobyclemson** [infrablocks/ruby_terraform#4]

**Comment by MAPontes** [comment]
Hi Toby,
Would be nice if you added the missing parameters. As WA I've been adding some parameters in the argument section of the code:
RubyTerraform.plan(
  directory: "-input=false src/*")

Just addin a comment to keep track of the issue if you ever work on it.
Awesome work btw.

Att.,
Marcelo Pontes

**Comment by tobyclemson** [comment]
Hey Marcelo,

What parameters are you using and for which commands? It would be useful to know so I can prioritise.

Thanks,
Toby

**Comment by MAPontes** [comment]
Hey Toby,

I'm using mostly the "-input" parameter on apply and plan so that I don't get prompted in case I forget a variable.

Att.,
Marcelo Pontes

**Comment by tobyclemson** [comment]
Looks good!

Merging now and will release shortly.
