### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by jesusbv** [infrablocks/ruby_terraform#43]
Hi,

In [this PR](https://github.com/infrablocks/ruby_terraform/pull/41/files) the changes should have been just the flag and not removing trailing spaces. I noticed it too late and it made me think if it would be ok to have some rules (e.g. `Rubocop`) in place.

**Comment by tobyclemson** [comment]
Hi Jesus, 

Yeah, I'd be happy to accept a PR including some linting.

Thanks,
Toby
