### ISSUE TITLE
Support for Terraform version 1.x

### ISSUE THREAD

**Issue by m8051** [infrablocks/ruby_terraform#78]
Howdy.

First of all, I'd like to thank you for this brilliant **gem**, I've been using it for the last 4 years to support my own Terraform Ruby Wrapper and automate most of my Infrastructure on AWS. 

At the moment I am working on upgrading our Terraform resources from versions 0.12 to v.1.0, I successfully managed to migrate our resources and code to v.0.15.5 along with some other minor changes in my Ruby Wrapper that uses the **RubyTerraform** gem.

According to the official guidelines [Upgrading to Terraform v1.0](https://www.terraform.io/language/upgrade-guides/1-0), this version is considered as a direct continuation of the v0.15 series and I wonder if you guys are actively working on supporting further versions of Terraform or if any of you have tested it with Terraform v1.0

**Comment by jonassvalin** [comment]
Hi @m8051 , thanks for your question. 
Ruby_terraform should be compatible with Terraform v1.0 already, we actively use [rake_terraform](https://github.com/infrablocks/rake_terraform) with Terraform 1.0 configurations already, see our [aws-encrypted-bucket](https://github.com/infrablocks/terraform-aws-encrypted-bucket/blob/main/Rakefile) as an example.

If there is functionality you're missing or you see unexpected behaviour then please let us know and we'll be happy to address it. We are committed to continued maintenance of ruby_terraform, we use it every day ourselves.
