### ISSUE TITLE
Feature request: plan.replace

### ISSUE THREAD

**Issue by jasonmk** [infrablocks/ruby_terraform#88]
From TF 0.15.2 and onward, the replace option to plan/apply is preferred to using the taint-apply combo.  It doesn't appear that ruby-terraform supports this option.  How difficult would it be to add?

More details here: https://www.terraform.io/cli/commands/plan#replace-address

Thanks!

**Comment by tobyclemson** [comment]
Hey @jasonmk,

This shouldn't be too hard to add and we'd happily accept a PR. Alternatively, if you are happy to wait a little while, we'll try to get to it in the next week or so.

Thanks,
Toby

**Comment by jasonmk** [comment]
Taking a look. Will adding to plan make it work with apply directly as well or would it have to be added to each?

**Comment by tobyclemson** [comment]
Looks good to me. I think even though 'replaces' sounds a little strange, it's consistent with the other pluralised parameters so I think it makes sense to stick with that.
